Resources:
    ExampleTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: ${self:provider.stackTags.name}-example
            BillingMode: PAY_PER_REQUEST
            StreamSpecification:
                StreamViewType: NEW_AND_OLD_IMAGES
            AttributeDefinitions:
                -
                    AttributeName: id
                    AttributeType: S
            KeySchema:
                -
                    AttributeName: id
                    KeyType: HASH