service: dynamodb-example
frameworkVersion: '3'
plugins:
    - serverless-plugin-bind-deployment-id
    - serverless-plugin-log-retention
    - serverless-deployment-bucket
    - serverless-dynamodb
    - serverless-python-requirements
    - serverless-offline
package:
    patterns:
        - '!.*'
        - '!.**/**'
        - '!infra/**'
        - '!node_modules/**'
        - '!Pipfile'
        - '!Pipfile.lock'
        - '!README.md'
        - '!serverless.yml'
        - '!package.json'
        - '!package-lock.json'
resources:
    - ${file(./infra/resources/dynamodb.yml)}
provider:
    name: aws
    runtime: python3.9
    architecture: arm64
    versionFunctions: false
    endpointType: regional
    stage: ${opt:stage, 'local'}
    region: ${opt:region, 'us-east-2'}
    stackName: ${self:provider.stackTags.name}
    apiName: ${self:provider.stackTags.name}
    deploymentBucket:
        name: ${self:provider.stackTags.name}-acai-aws-examples
    stackTags:
        name: ${opt:stage, 'local'}-${self:service}
        service: ${self:service}
        environment: ${opt:stage, 'local'}
        managed-by: serverless-framework
custom:
    logRetentionInDays: 1
    pythonRequirements:
        useDownloadCache: false
        useStaticCache: false
        usePoetry: false
        usePipenv: true
        dockerizePip: non-linux
        dockerImage: public.ecr.aws/sam/build-python3.9:latest
        slim: true
        slimPatternsAppendDefaults: true
        slimPatterns:
            - '**/*.py[c|o]'
            - '**/__pycache__*'
    serverless-dynamodb:
        stages:
            - local
        start:
            port: 4001
            inMemory: true
            migrate: true
            seed: true
        seed:
            cache:
                sources:
                    -
                        table: ${self:provider.stackTags.name}-example
                        sources: [./infra/local/seed/test.json]
functions:
    v1-ddb-stream-handler:
        name: ${self:provider.stackTags.name}-v1-ddb-stream-handler
        handler: app/handler.stream
        description: example ddb handler
        memorySize: 256
        events:
            - stream:
                type: dynamodb
                arn:
                    Fn::GetAtt: [ExampleTable, StreamArn]
